packages:
  - '.'
  - 'client'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msw: true
  postinstall-postinstall: true
  sharp: true
minimumReleaseAgeExclude:
  - '@axhub/commentary-react@1.0.0'
